/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    letters: Letter;
    products: Product;
    subscribers: Subscriber;
    'upcoming-sessions': UpcomingSession;
    'topic-suggestions': TopicSuggestion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    letters: LettersSelect<false> | LettersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'upcoming-sessions': UpcomingSessionsSelect<false> | UpcomingSessionsSelect<true>;
    'topic-suggestions': TopicSuggestionsSelect<false> | TopicSuggestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-content': HomeContent;
    'sessions-content': SessionsContent;
    'letters-content': LettersContent;
    'products-content': ProductsContent;
    'booking-content': BookingContent;
    'email-templates': EmailTemplate;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'sessions-content': SessionsContentSelect<false> | SessionsContentSelect<true>;
    'letters-content': LettersContentSelect<false> | LettersContentSelect<true>;
    'products-content': ProductsContentSelect<false> | ProductsContentSelect<true>;
    'booking-content': BookingContentSelect<false> | BookingContentSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters".
 */
export interface Letter {
  id: number;
  title: string;
  /**
   * URL path — e.g. from-chaos-to-structure
   */
  slug: string;
  kind: 'Insight' | 'Framework' | 'Story + lesson' | 'Contrarian';
  publishedAt: string;
  dek: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  format: 'Ebook' | 'Workbook' | 'Course';
  blurb?: string | null;
  cover?: (number | null) | Media;
  /**
   * What the buyer receives after paying — sent as a download link by email once Stripe confirms payment.
   */
  file?: (number | null) | Media;
  /**
   * Leave blank to show as TBC. Checkout runs on Stripe.
   */
  priceUSD?: number | null;
  /**
   * Leave blank to show as TBC.
   */
  priceGBP?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who signed up for the letters. Emailed automatically on a new letter or product, and once on sign-up. Managed by the site — not meant to be added to by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  status: 'active' | 'unsubscribed';
  unsubscribeToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dates you're publishing on /calendar as upcoming Clarity Sessions -- independent of live Cal.com booking availability. Add as many as you like, for the quarter or the whole year; past dates stop showing automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-sessions".
 */
export interface UpcomingSession {
  id: number;
  date: string;
  /**
   * Optional note, e.g. "Group session" or "Applications open". Leave blank for a plain date.
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submitted via the "suggest a topic" form on /calendar. New entries can't be added by visitors directly (only through that form) -- but you can freely edit the text, set a status, and leave yourself notes here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-suggestions".
 */
export interface TopicSuggestion {
  id: number;
  suggestion: string;
  name?: string | null;
  email?: string | null;
  status: 'New' | 'Considering' | 'Planned' | 'Done';
  /**
   * Not shown publicly -- your own notes on this suggestion.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'letters';
        value: number | Letter;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'upcoming-sessions';
        value: number | UpcomingSession;
      } | null)
    | ({
        relationTo: 'topic-suggestions';
        value: number | TopicSuggestion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters_select".
 */
export interface LettersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  publishedAt?: T;
  dek?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  format?: T;
  blurb?: T;
  cover?: T;
  file?: T;
  priceUSD?: T;
  priceGBP?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upcoming-sessions_select".
 */
export interface UpcomingSessionsSelect<T extends boolean = true> {
  date?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic-suggestions_select".
 */
export interface TopicSuggestionsSelect<T extends boolean = true> {
  suggestion?: T;
  name?: T;
  email?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the footer and used as the fallback contact address across the site (booking/order confirmation pages, etc.).
   */
  contactEmail: string;
  seo: {
    title: string;
    description: string;
  };
  introSession: {
    minutes: number;
    description?: string | null;
  };
  /**
   * Each row is a bookable length with its price. Add more rows for additional duration options. Checkout runs on Stripe (USD/GBP).
   */
  paidTiers?:
    | {
        minutes: number;
        /**
         * Leave blank to show as TBC.
         */
        priceUSD?: number | null;
        /**
         * Leave blank to show as TBC.
         */
        priceGBP?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  /**
   * Rotates automatically on the homepage hero. Each row is one quote, split across two lines.
   */
  heroQuotes?:
    | {
        line1: string;
        line2: string;
        id?: string | null;
      }[]
    | null;
  heroSubhead?: string | null;
  model?: {
    heading?: string | null;
    intro?: string | null;
    stages?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  pillars?: {
    heading?: string | null;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  testimonial?: {
    quote?: string | null;
    attribution?: string | null;
  };
  about?: {
    paragraph1?: string | null;
    paragraph2?: string | null;
    /**
     * Add one or more photos — they rotate automatically. Falls back to a default photo if left empty.
     */
    photos?:
      | {
          photo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  teachings?: {
    /**
     * Paste the full YouTube link (youtu.be/... or youtube.com/watch?v=...) or just the video ID -- either works. Leave blank to show a placeholder that links to the channel instead.
     */
    videos?:
      | {
          title: string;
          videoId?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  community?: {
    heading?: string | null;
    text?: string | null;
  };
  letter?: {
    heading?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions-content".
 */
export interface SessionsContent {
  id: number;
  heroIntro?: string | null;
  /**
   * The first point always shows the live session length; these two follow it.
   */
  extraSessionPoints?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  howItRuns?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  afterwards?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonial?: {
    quote?: string | null;
    attribution?: string | null;
  };
  nextOpeningCtaLabel: string;
  tiers: {
    heading: string;
    community: {
      eyebrow: string;
      title: string;
      bullets?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      ctaLabel: string;
    };
    intro: {
      eyebrow: string;
      title: string;
      /**
       * The intro session's length is inserted live before these — leave this to just the points that follow it.
       */
      bullets?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      ctaLabel: string;
    };
    paid: {
      eyebrow: string;
      /**
       * The session length is inserted live before these — leave this to just the points that follow it.
       */
      bullets?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      ctaLabel: string;
      footnote: string;
    };
  };
  bottomCta: {
    heading: string;
    text: string;
    ctaLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters-content".
 */
export interface LettersContent {
  id: number;
  heading: string;
  subhead: string;
  loadMoreLabel: string;
  emptyStateText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-content".
 */
export interface ProductsContent {
  id: number;
  heading: string;
  subhead: string;
  ctaLabel: string;
  ctaCaption: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-content".
 */
export interface BookingContent {
  id: number;
  heading: string;
  communityTeaser: {
    text: string;
    ctaLabel: string;
  };
  held: {
    heading: string;
    againLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Automated emails sent to subscribers. Use {{ }} placeholders — each template lists which ones it supports.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * Placeholders: {{unsubscribeUrl}}
   */
  welcome: {
    subject: string;
    body: string;
  };
  /**
   * Placeholders: {{title}}, {{dek}}, {{url}}, {{unsubscribeUrl}}
   */
  newLetter: {
    subject: string;
    body: string;
  };
  /**
   * Placeholders: {{title}}, {{blurb}}, {{url}}, {{unsubscribeUrl}}
   */
  newProduct: {
    subject: string;
    body: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactEmail?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  introSession?:
    | T
    | {
        minutes?: T;
        description?: T;
      };
  paidTiers?:
    | T
    | {
        minutes?: T;
        priceUSD?: T;
        priceGBP?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  heroQuotes?:
    | T
    | {
        line1?: T;
        line2?: T;
        id?: T;
      };
  heroSubhead?: T;
  model?:
    | T
    | {
        heading?: T;
        intro?: T;
        stages?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pillars?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  testimonial?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  about?:
    | T
    | {
        paragraph1?: T;
        paragraph2?: T;
        photos?:
          | T
          | {
              photo?: T;
              id?: T;
            };
      };
  teachings?:
    | T
    | {
        videos?:
          | T
          | {
              title?: T;
              videoId?: T;
              id?: T;
            };
      };
  community?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  letter?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions-content_select".
 */
export interface SessionsContentSelect<T extends boolean = true> {
  heroIntro?: T;
  extraSessionPoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  howItRuns?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  afterwards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  nextOpeningCtaLabel?: T;
  tiers?:
    | T
    | {
        heading?: T;
        community?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
            };
        intro?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
            };
        paid?:
          | T
          | {
              eyebrow?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              footnote?: T;
            };
      };
  bottomCta?:
    | T
    | {
        heading?: T;
        text?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters-content_select".
 */
export interface LettersContentSelect<T extends boolean = true> {
  heading?: T;
  subhead?: T;
  loadMoreLabel?: T;
  emptyStateText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-content_select".
 */
export interface ProductsContentSelect<T extends boolean = true> {
  heading?: T;
  subhead?: T;
  ctaLabel?: T;
  ctaCaption?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-content_select".
 */
export interface BookingContentSelect<T extends boolean = true> {
  heading?: T;
  communityTeaser?:
    | T
    | {
        text?: T;
        ctaLabel?: T;
      };
  held?:
    | T
    | {
        heading?: T;
        againLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  welcome?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  newLetter?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  newProduct?:
    | T
    | {
        subject?: T;
        body?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}